### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by udnp**
Hi, Night Screen app team.

This PR is miner improvement for Japanese translation.
Would you check this?
Thanks.

### CODE REVIEW

**Comment by fython** [comment]
Thanks for improving translation.

**Comment by udnp** [comment]
Thank you for merging this.
And I'm sorry about my mistake for this PR title.
So I corrected it.

**Comment by fython** [comment]
@udnp That's okay. These days I add some new strings for new UI. Translations can be updated again if you have extra time.

**Comment by udnp** [comment]
@fython 
That sounds good!
I will try it.

**Pull request merged**
